language: generic
install:
- source ./.texlive-ci/texlive_install.sh
- sudo ./.texlive-ci/pdf2htmlex_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
  - "/tmp/dependency_builds"
before_script: cd $TRAVIS_BUILD_DIR
script:
- python .texlive-ci/texlive_build.py ".*/latex/.*\.tex" --deploy out/
