language: generic
install:
- source ./texlive-ci/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_script: cd $TRAVIS_BUILD_DIR
script:
- python texlive-ci/texlive_build.py ".*/latex/.*\.tex"
- find | sed 's|[^/]*/|- |g'

