language: generic
install:
- source ./texlive-ci/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_script: cd $TRAVIS_BUILD_DIR
script:
- python texlive-ci/texlive_build.py ".*/latex/.*\.tex" --deploy out/
- find | sed 's|[^/]*/|- |g'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out/
  on:
    branch: master
